
import { makeStore } from '@/lib/store';
import type { Metadata } from 'next'
import { Noto_Sans_Thai } from 'next/font/google'
import StoreProvider from './StoreProvider';
const inter = Noto_Sans_Thai({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
